### ISSUE TITLE
Typo when receiving "Skeleton hatching potion"

### ISSUE THREAD

**Issue by gp2015** [HabitRPG/habitica-ios#287]
When receiving the skeleton hatching potion on the iOS version, the notification displays no space between "hatching" and "potion".

**Comment by carroux** [comment]
I've also experienced this--it seems to happen when receiving any kind of hatching potion. I'm running the latest version of the app (1.1.1) on the latest version of iOS (9.1).

>"You found a White HatchingPotion!"

![img_8860](https://cloud.githubusercontent.com/assets/5157761/10993445/b34fbdba-8423-11e5-8961-70631426918f.PNG)

**Comment by gp2015** [comment]
I would love to contribute to this project, might be starting in a few days - I need to get familiar with some of the technology used and get an environment setup. If anyone has any resources to guide me through getting started, or wants to help, I could most likely fix this issue myself.

**Comment by vIiRuS** [comment]
@gp2015 awesome!

I can write up the reason this happens and my idea for a fix later today.

If you have any problems getting the app set up locally, let me know!

**Comment by amecila** [comment]
@vIiRuS could you share why this happens? It seems like a small fix but looking through the code I have no idea where one would even begin!

**Comment by vIiRuS** [comment]
Currently the drop notification text is constructed on the device. I now noticed that there is also a "dialog" field for each item that can drop. The simple (and probably correct) fix for this would be to simply change the code to use the existing dialog field, since that one also respects locale and the current solution doesn't.

Note that the library that is currently displaying the in-app notifications doesn't display long text that well (iirc). As the text from the dialog field is longer than the current texts, that might be a problem. Since the notification library has some other issues and doesn't seem to be maintained anymore, I am planning on replacing it anyway though.

**Comment by a-ayyash** [comment]
Hey there, I downloaded the base project and ran it to be able to trace this issue and it looks like it's originated in this [line](https://github.com/HabitRPG/habitrpg/blob/develop/common/script/fns/randomDrop.js#L72), So I'm going to make a PR for it on the other repo if that's ok.

**Comment by vIiRuS** [comment]
No, that string is intentionally without the space. It's not intended to be human readable. I think using the dialog field from the response, as I outlined in my previous comment, would be the better solution.

**Comment by a-ayyash** [comment]
isn't [this](https://github.com/HabitRPG/habitrpg-ios/blob/5db2612131899a0992d982eca91f8c2653a63a1a/HabitRPG/HRPGManager.m#L432) already the case ?

**Comment by a-ayyash** [comment]
@vIiRuS bump.
