### ISSUE TITLE
Rest in the Inn has no explanation

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-ios#298]
Lately, the Tavern has been getting a LOT of questions about what resting in the inn is for. I'm pretty sure most would be from iOS users since the website has an explanation. Can a brief description be added to rest in the inn button, perhaps with a "more info" link or something for a full explanation?

**Comment by Alys** [comment]
pinging @lemoness

**Comment by lemoness** [comment]
So, there are two directions that we could go for this.

1) Keep the text as "Rest in the Inn" and provide an explanation.

2. Change the button to something more descriptive, such as "Pause my Dailies", and include the phrase "Rest in the Inn" in the flavor text. (We would make this change on Android, iOS, and the website for consistency.)

Personally, I'm leaning towards the second option. I know it has less flavor, but it's much more clear, since more people will read the text on the button than the text underneath. That being said, I know it's a bit controversial, so I am open to debate. 

If we go with the second option, I would recommend something like:

PAUSE MY DAILIES
Rest in the Inn to prevent your Dailies from hurting you overnight! (Note: does not prevent Boss damage.)

**Comment by Alys** [comment]
Slightly sadly, I think you're right about the second option being best. Clarity is more important than flavour.

Is "pause" the best term? Will that confuse people when they see their Dailies becoming unticked? Not arguing, just wondering.

I think it would be helpful to specify that it does prevent boss damage FROM you but not TO you. I can see that being a question. Is this too long?
"Rest in the Inn to prevent your Dailies from hurting you and your party overnight! (Note: does not prevent Boss damage to you from party mates.)"

**Comment by lemoness** [comment]
How about "Prevent Daily Damage"? Personally, I think it's a bit more
unwieldy. We could try out "Pause Your Dailies" and see what kinds of
questions we get. Will keep brainstorming.

IMO "hurting you and your party" makes it sound like you're always at risk
of hurting your party. How about this?
"Rest in the Inn to prevent your undone Dailies from hurting you overnight!
(Note: does not prevent you from receiving Boss damage.)"

**Comment by Alys** [comment]
Android version of this issue: https://github.com/HabitRPG/habitrpg-android/issues/495
