### ISSUE TITLE
GPL incompatible with App Store

### ISSUE THREAD

**Issue by wwahammy** [HabitRPG/habitica-ios#318]
As of 2010 (and I'd assume this hasn't changed), Apple's App store agreement prevented the distribution of GPL'd software on the App Store [https://www.fsf.org/news/2010-05-app-store-compliance].  This would seem to imply that there may be some issues with this repo being under the GPL since it will be distributed via the App Store. To fix this, an exception could be added to the GPL for inclusion in the App Store with agreement of the copyright holders.

**Comment by lazerwalker** [comment]
Yes, this is still true, and would theoretically be grounds for someone to complain to Apple to get the app taken down.

Specifically, anyone contributing to the iOS app would need to sign a CLA that assigns copyright to Habitica, since only the copyright owner of a piece of GPL'd code is allowed to grant an exception.

Historically, this has caused issues in the past with a few GPLed iOS apps (Battle for Wesnoth, VLC) where individual contributors objected to the use of their code in an environment where they hadn't signed a CLA or granted that exception.

**Comment by veeeeeee** [comment]
We're aware of this issue, but removing it from Github so as not to complicate development efforts and organization.
