### ISSUE TITLE
Daily streak reset on connection lost

### ISSUE THREAD

**Issue by aeonzh** [HabitRPG/habitica-ios#331]
When the app momentarily losts connection under any case it resets every daily task streak counter, although it's possible to fix the value manually it's pretty annoying.

**Comment by vIiRuS** [comment]
Can you maybe elaborate on this? which action causes the streaks to reset when the network request fails? (I could'nt reproduce this with a simple pull-to-refresh). Also, what exactly do you mean by fixing it manually?

**Comment by AeonZh** [comment]
When I tick a task, unaware that my device is not connected to the Internet or it switches from Wi-fi to mobile data the streak counter resets, because when I reconnect, I refresh to re-tick the task and the streak counter says 1 when I had previously a greater value.
By fix it manually I mean changing the streak value under the "Advanced Option" on the site

**Comment by vIiRuS** [comment]
Is it possible that this is because the daily is missed because the action is not synced and when cron occures the daily isn't checked? Because that would explain this behaviour. You can check if this is the case, if this happening also causes you to loose health.

**Comment by AeonZh** [comment]
By fixing manually I mean restoring the value through "advanced option".
Rigth now I can't reproduce the event myself to confirm, but I'm pretty sure it was happening no matter the time.
