### ISSUE TITLE
"Egg Hunt" quest pets do not have a green feed bar

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-ios#397]
The "Egg" pets from the [Egg Hunt quest](http://habitica.wikia.com/wiki/Egg_Hunt) do not have feed bars, even though they can be fed.

This would be because it used to be impossible to feed them, so the app contained some code to hide the feed bar. Finding and removing that code should (I think) be all that's needed.

**Comment by jakers821** [comment]
I would like to help with this.

**Comment by bleepnik** [comment]
The same is true of special pets, such as those hatched with royal purple or cupid potion. Not sure if the issue is the same, or just the symptoms. If the cause is different, I can create a new issue. I didn't find out until today that cupid potion-hatched pets can be fed and grown to mounts; having lost so much time, I hurriedly stockpiled cupid potions so I can keep at it after the 28th. =)

**Comment by saraolson** [comment]
Is this fixed and ready to close? Can anyone test?

**Comment by fiuzaB** [comment]
Just tested on an iPhone 4S device and the feed bar is still missing.
