### ISSUE TITLE
Class is not displayed in users profile

### ISSUE THREAD

**Issue by Ieahleen** [HabitRPG/habitica-ios#455]
It's possible to see our own class, but visiting the profile of other users it's not possibile to see theirs, you can see everything else but Class and User ID.
[Here Alys profile as an example](https://drive.google.com/open?id=0B213ebNsVd4TcDZVck5zMi1PczA)

![image](https://cloud.githubusercontent.com/assets/1495809/24398143/dbc9381c-13eb-11e7-9fd2-e1f42edc9559.png)

**Comment by Alys** [comment]
Here's the same profile from the Android app, showing the class:

![image](https://cloud.githubusercontent.com/assets/1495809/24398212/11ca9776-13ec-11e7-8afe-68e4ae23695a.png)


Lower down on the same screen on the Android app is the User ID with a useful copy button - it would be good to have those in profiles on the iOS app too.

![image](https://cloud.githubusercontent.com/assets/1495809/24398276/407ee45a-13ec-11e7-9092-ad2a1cbb4f72.png)

**Comment by saraolson** [comment]
I'm adding the design tag because profiles need a rehaul, but since that won't happen for awhile, leaving the help wanted tag for the smaller ui changes in the meantime

**Comment by delightedCrow** [comment]
I'd like to take a crack at this one if it's still relevant

**Comment by delightedCrow** [comment]
Since there are so many ways to implement this I thought I’d do a couple of quick n dirty mockups to show the two routes I think make the most sense, though I’m leaning toward solution 2. 

### Solution 1: 
Add the class label underneath the stat bars where the Level currently is:
![mock-header](https://user-images.githubusercontent.com/480192/66076024-b9726f00-e511-11e9-9de7-22995f369783.png)


Pros: The info is in the same place as before, might look more consistent with the android app?
Cons: having so much info in such a small place makes the whole design feel cramped and busy

### Solution 2:
Move the Class/Level info into a table row underneath the Username:
![mock-tablerow](https://user-images.githubusercontent.com/480192/66076048-c8592180-e511-11e9-949d-cf64f68b7839.png)


Pros: The header area feels less cluttered, keeps the design a bit more consistent since all the other user stats (bio, username, etc) are down  in the tableview, less fiddly to implement than solution 1.

Again, I’m leaning toward Solution 2, but I thought I’d lay out my reasoning in case there are design considerations I’m not aware of.
