### ISSUE TITLE
'Habitica-Swift.h' file not found

### ISSUE THREAD

**Issue by schomes** [HabitRPG/habitica-ios#463]
I'm getting this compilation error:

`/HabitRPG/HRPGAppDelegate.m:29:9: 'Habitica-Swift.h' file not found`

The error occurs in `HRPGAppDelegate.m` here:
`#import "Habitica-Swift.h"`

I searched the project for the file (using `find . -name "Habitica-Swift.h"`) and found nothing. My idea for a fix is to delete the line where this issue occurs, but since I'm not sure if it is needed, I would like some feedback on this first.

**Comment by vIiRuS** [comment]
That import is needed, because otherwise the ObjC classes can not access
the swift classes. The file isn't in the project, because it is generated
by xcode. Since you mentioned in the other issue, that you also have the
keys issue, that probably prevents xcode from generating the bridge header.

-- 
Phillip Thelen
Sent with Airmail

**Comment by schomes** [comment]
Running `pod install` again fixed this issue. As you said, the keys issue was responsible for this one. See resolution of #462.
